'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Namespace lab_50_API_Framework

    Partial Public Class NorthwindEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=NorthwindEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property C__EFMigrationsHistory() As DbSet(Of C__EFMigrationsHistory)
        Public Overridable Property Categories() As DbSet(Of Category)
        Public Overridable Property CustomerDemographics() As DbSet(Of CustomerDemographic)
        Public Overridable Property Customers() As DbSet(Of Customer)
        Public Overridable Property Employees() As DbSet(Of Employee)
        Public Overridable Property Order_Details() As DbSet(Of Order_Detail)
        Public Overridable Property Orders() As DbSet(Of Order)
        Public Overridable Property Products() As DbSet(Of Product)
        Public Overridable Property Regions() As DbSet(Of Region)
        Public Overridable Property Shippers() As DbSet(Of Shipper)
        Public Overridable Property Suppliers() As DbSet(Of Supplier)
        Public Overridable Property Territories() As DbSet(Of Territory)
        Public Overridable Property ToDoItems() As DbSet(Of ToDoItem)
        Public Overridable Property Alphabetical_list_of_products() As DbSet(Of Alphabetical_list_of_product)
        Public Overridable Property Category_Sales_for_1997() As DbSet(Of Category_Sales_for_1997)
        Public Overridable Property Current_Product_Lists() As DbSet(Of Current_Product_List)
        Public Overridable Property Customer_and_Suppliers_by_Cities() As DbSet(Of Customer_and_Suppliers_by_City)
        Public Overridable Property Invoices() As DbSet(Of Invoice)
        Public Overridable Property Order_Details_Extendeds() As DbSet(Of Order_Details_Extended)
        Public Overridable Property Order_Subtotals() As DbSet(Of Order_Subtotal)
        Public Overridable Property Orders_Qries() As DbSet(Of Orders_Qry)
        Public Overridable Property Product_Sales_for_1997() As DbSet(Of Product_Sales_for_1997)
        Public Overridable Property Products_Above_Average_Prices() As DbSet(Of Products_Above_Average_Price)
        Public Overridable Property Products_by_Categories() As DbSet(Of Products_by_Category)
        Public Overridable Property Sales_by_Categories() As DbSet(Of Sales_by_Category)
        Public Overridable Property Sales_Totals_by_Amounts() As DbSet(Of Sales_Totals_by_Amount)
        Public Overridable Property Summary_of_Sales_by_Quarters() As DbSet(Of Summary_of_Sales_by_Quarter)
        Public Overridable Property Summary_of_Sales_by_Years() As DbSet(Of Summary_of_Sales_by_Year)
    
        Public Overridable Function CustOrderHist(customerID As String) As ObjectResult(Of CustOrderHist_Result)
            Dim customerIDParameter As ObjectParameter = If(customerID IsNot Nothing, New ObjectParameter("CustomerID", customerID), New ObjectParameter("CustomerID", GetType(String)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CustOrderHist_Result)("CustOrderHist", customerIDParameter)
        End Function
    
        Public Overridable Function CustOrdersDetail(orderID As Nullable(Of Integer)) As ObjectResult(Of CustOrdersDetail_Result)
            Dim orderIDParameter As ObjectParameter = If(orderID.HasValue, New ObjectParameter("OrderID", orderID), New ObjectParameter("OrderID", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CustOrdersDetail_Result)("CustOrdersDetail", orderIDParameter)
        End Function
    
        Public Overridable Function CustOrdersOrders(customerID As String) As ObjectResult(Of CustOrdersOrders_Result)
            Dim customerIDParameter As ObjectParameter = If(customerID IsNot Nothing, New ObjectParameter("CustomerID", customerID), New ObjectParameter("CustomerID", GetType(String)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CustOrdersOrders_Result)("CustOrdersOrders", customerIDParameter)
        End Function
    
        Public Overridable Function Employee_Sales_by_Country(beginning_Date As Nullable(Of Date), ending_Date As Nullable(Of Date)) As ObjectResult(Of Employee_Sales_by_Country_Result)
            Dim beginning_DateParameter As ObjectParameter = If(beginning_Date.HasValue, New ObjectParameter("Beginning_Date", beginning_Date), New ObjectParameter("Beginning_Date", GetType(Date)))
    
            Dim ending_DateParameter As ObjectParameter = If(ending_Date.HasValue, New ObjectParameter("Ending_Date", ending_Date), New ObjectParameter("Ending_Date", GetType(Date)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Employee_Sales_by_Country_Result)("Employee_Sales_by_Country", beginning_DateParameter, ending_DateParameter)
        End Function
    
        Public Overridable Function Sales_by_Year(beginning_Date As Nullable(Of Date), ending_Date As Nullable(Of Date)) As ObjectResult(Of Sales_by_Year_Result)
            Dim beginning_DateParameter As ObjectParameter = If(beginning_Date.HasValue, New ObjectParameter("Beginning_Date", beginning_Date), New ObjectParameter("Beginning_Date", GetType(Date)))
    
            Dim ending_DateParameter As ObjectParameter = If(ending_Date.HasValue, New ObjectParameter("Ending_Date", ending_Date), New ObjectParameter("Ending_Date", GetType(Date)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Sales_by_Year_Result)("Sales_by_Year", beginning_DateParameter, ending_DateParameter)
        End Function
    
        Public Overridable Function SalesByCategory(categoryName As String, ordYear As String) As ObjectResult(Of SalesByCategory_Result)
            Dim categoryNameParameter As ObjectParameter = If(categoryName IsNot Nothing, New ObjectParameter("CategoryName", categoryName), New ObjectParameter("CategoryName", GetType(String)))
    
            Dim ordYearParameter As ObjectParameter = If(ordYear IsNot Nothing, New ObjectParameter("OrdYear", ordYear), New ObjectParameter("OrdYear", GetType(String)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SalesByCategory_Result)("SalesByCategory", categoryNameParameter, ordYearParameter)
        End Function
    
        Public Overridable Function Ten_Most_Expensive_Products() As ObjectResult(Of Ten_Most_Expensive_Products_Result)
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Ten_Most_Expensive_Products_Result)("Ten_Most_Expensive_Products")
        End Function
    
    End Class

End Namespace
