'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace lab_50_API_Framework

    Partial Public Class ToDoItem
        Public Property ToDoItemId As Integer
        Public Property ToDoItemName As String
        Public Property DateCreated As Date
    
    End Class

End Namespace
